In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [5]:
ones = np.ones((2, 4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
ones.sum(axis=0)

array([2., 2., 2., 2.])

In [7]:
ones.sum(axis=1)

array([4., 4.])

In [8]:
1 - ones

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
ones * ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
ones.ndim

2

In [12]:
from common.layers import Sigmoid
sigmoid = Sigmoid()
sigmoid.forward(ones)

array([[0.73105858, 0.73105858, 0.73105858, 0.73105858],
       [0.73105858, 0.73105858, 0.73105858, 0.73105858]])

In [13]:
sigmoid.out

array([[0.73105858, 0.73105858, 0.73105858, 0.73105858],
       [0.73105858, 0.73105858, 0.73105858, 0.73105858]])

In [17]:
dout = np.arange(0, 8).reshape(2, 4)
sigmoid.backward(dout)

array([[0.        , 0.19661193, 0.39322387, 0.5898358 ],
       [0.78644773, 0.98305967, 1.1796716 , 1.37628353]])

In [18]:
np.array(np.array([1,0, -3, -5,6,7]) > 0, dtype=np.int32)

array([1, 0, 0, 0, 1, 1])

In [20]:
s = np.random.dirichlet((10, 3), 20).transpose()
s

array([[0.52358115, 0.79216489, 0.61957747, 0.7362386 , 0.65302009,
        0.82111844, 0.71388413, 0.85279883, 0.83233847, 0.72436588,
        0.75488372, 0.74281702, 0.85105497, 0.87534427, 0.86945925,
        0.60861834, 0.46664472, 0.72795347, 0.73893307, 0.86077736],
       [0.47641885, 0.20783511, 0.38042253, 0.2637614 , 0.34697991,
        0.17888156, 0.28611587, 0.14720117, 0.16766153, 0.27563412,
        0.24511628, 0.25718298, 0.14894503, 0.12465573, 0.13054075,
        0.39138166, 0.53335528, 0.27204653, 0.26106693, 0.13922264]])